channels:
  - conda-forge
  - nodefaults
dependencies:
  # setuptools 72.x breaks `test` and `test_suite`.
  # [72.1.0](https://setuptools.pypa.io/en/stable/history.html#v72-1-0)
  # restores `test`, but `test_suite`still doesn't work right.
  - setuptools <= 72.0
  - python>=3.7,<3.9
  - numpy
  - scipy
  - matplotlib-base
  - packaging
  - mayavi
  - gmsh <4.0|>=4.5.2
  - mpich
  - mpi4py
  - pytrilinos
  - pip
  - pip:
    - steppyngstounes
platforms:
  - linux-64
  - osx-64
